import { Blog, Category, Role, Tag, User } from "entity";

export const mockupRoles: Array<Role> = [
  {
    id: 1,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Admin",
  },
  {
    id: 2,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "User",
  },
];

export const mockupUsers: Array<User> = [
  {
    id: 1,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    fullName: "Admin",
    email: "admin@gmail.com",
    roleId: 1,
    phone: "123123123",
    banned: false,
    confirmed: true,
    role: mockupRoles[0],
    rolePermissions: [],
  },
  {
    id: 2,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    fullName: "User",
    email: "user@gmail,com",
    roleId: 2,
    phone: "123123123",
    banned: false,
    confirmed: true,
    role: mockupRoles[1],
    rolePermissions: [],
  },
];

export const mockupTags: Array<Tag> = [
  {
    id: 1,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Tag 1",
    slug: "tag-1",
  },
  {
    id: 2,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Tag 2",
    slug: "tag-2",
  },
];

export const mockupCategories: Array<Category> = [
  {
    id: 1,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Technology",
    slug: "technology",
  },
  {
    id: 2,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Sport",
    slug: "sport",
  },
  {
    id: 3,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Food",
    slug: "food",
  },
  {
    id: 4,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Travel",
    slug: "travel",
  },
  {
    id: 5,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Fashion",
    slug: "fashion",
  },
  {
    id: 6,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Economics",
    slug: "economics",
  },
  {
    id: 7,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Health",
    slug: "health",
  },
  {
    id: 8,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Science",
    slug: "science",
  },
  {
    id: 9,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Entertainment",
    slug: "entertainment",
  },
  {
    id: 10,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Cryptocurrency",
    slug: "cryptocurrency",
  },
  {
    id: 11,
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Business",
    slug: "business",
  },
];

export const mockupBlogs: Array<Blog> = [
  {
    id: 1,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 1",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-1",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 2,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 2",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-2",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 3,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 3",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-3",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 4,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 4",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-4",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 5,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 5",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-5",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 6,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 6",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-6",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 7,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 7",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-7",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
  {
    id: 8,
    thumbnailPath: "/images/oldman.jpg",
    createdAt: "2023-06-03",
    updatedAt: "2023-06-03",
    title: "Blog 8",
    content:
      "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
    views: 0,
    disabled: false,
    slug: "blog-8",
    categoryId: 1,
    category: mockupCategories[0],
    tags: mockupTags,
    comments: [],
    createdBy: 1,
    user: mockupUsers[0],
  },
];
